POST http://localhost:8070/apis/rest/languages
Content-Type: application/json

{
  "name": "LALALAL"
}

###

POST http://localhost:8070/apis/rest/languages
Content-Type: application/xml

<LanguageFormDto>
    <name>Italian1</name>
</LanguageFormDto>

###

PUT http://localhost:8070/apis/rest/languages/9
Content-Type: application/json

{
  "name": "LALALA"
}

###
GET http://localhost:8070/apis/rest/languages HTTP/1.1

###

GET http://localhost:8070/apis/rest/languages/1 HTTP/1.1
