POST http://localhost:8070/apis/rest/staffs
Content-Type: application/json

{
  "firstName": "Rola",
  "lastName": "Mohamed",
  "picture": null,
  "email": "rola@gmail.com",
  "active": true,
  "username": "rola_mohamed",
  "password": "123456",
  "address": "cairo",
  "district": "cairo",
  "city": "3",
  "country": "101",
  "postalCode": "12345",
  "phone": "01112345678",
  "storeID": "4"
}

###

PUT http://localhost:8070/apis/rest/staffs/6
Content-Type: application/json

{
  "firstName": "Rola",
  "lastName": "Mohamed",
  "picture": null,
  "email": "rola_mohamed@gmail.com",
  "active": true,
  "username": "rola_mohamed",
  "password": "123456",
  "address": "cairo",
  "district": "cairo",
  "city": "3",
  "country": "101",
  "postalCode": "12345",
  "phone": "01112345678",
  "storeID": "4"
}

###
GET http://localhost:8070/apis/rest/staffs HTTP/1.1

###

GET http://localhost:8070/apis/rest/staffs/1 HTTP/1.1
